### ISSUE TITLE
GUI "Save as" button will not let me fill in a name

### ISSUE THREAD

**Issue by ericfont** [moddevices/mod-duo-issues#44] opened 2016-05-31 03:52 UTC
Let me first note that in the past I have had no problem with inputting names, but it is summer now and my labtop is hot right now, and so is running at only 1GHz.   (It has also worked just fine on my chromebook which doesn't get hot.)  Anyway, if I create a new pedalboard and click "Save as", I see a blank line where I should be able to type, but if I try to click on or near that line and start typing, nothing happens.  After pressing the save button, then it says A new pedalboard "" has been created.  I'm also noticing the problem when creating a new bank, I'm unable to name the new bank.  Fails on both firefox and midori.  But everything else in the gui seems to work.  It might be possible to simulate a low cpu frequency to reproduce this bug, but I haven't looked into that.

**Comment by ericfont** [comment] 2016-05-31 18:25
I'm veryifying that this problem does indeed result from a hot computer.  I've just tried again with a fresh boot of my labtop after it had cooled down, and both the "Save as" and +Add Bank allows me to actually fill in the name.  I find the same thing happens regardless of what browser I used: Firefox, Chrome, or Midori.

**Comment by odurc** [comment] 2016-06-01 14:19
I'm happy you sorted out the problem with "Save as" and I see you found a new bug. You shouldn't be able to save a pedalboard without a name. I'm closing this issue and open a new one. Thanks.

**Closed as completed by odurc** 2016-06-01 14:19 UTC

**Comment by ntonnaett** [comment] 2016-06-05 10:11
I also encountered that bug. And it's not related to a hot cpu. The problem is that I can't figure out how to reproduce it.

**Comment by ericfont** [comment] 2016-06-05 12:01
ok, sorry my mistaken hypothesis.  Any other ideas?

**Comment by ericfont** [comment] 2016-09-30 06:10
Just to clarifying, the problem never had anything to do with a hot labtop.  But the problem was fixed during some release since this issue was reported.
