### ISSUE TITLE
UI locks up after boot with a certain pedalboard

### ISSUE THREAD

**Issue by MrBollie** [moddevices/mod-duo-issues#83] opened 2016-11-13 19:46 UTC
## Description

Starting up the MOD with a specific pedalboard locks up the MOD Duo.
 
## Expected/suggested solution

I suspect MDA Leslie to cause the lock ups, but I'm not quite sure. I'll attach the pedalboard file.
In order to get rid of that pedalboard, I set default.pedalboard in ~/data/last.json to be able to boot again.

## Additional information
* release: v1.2.0
* controller: 4bac7f9
* Operating system: Linux
* System version: ARCH

File: 
[BollieWet.pedalboard.zip](https://github.com/moddevices/mod-duo-issues/files/588015/BollieWet.pedalboard.zip)

**Comment by falkTX** [comment] 2016-12-02 09:21
I can confirm the issue.
Investigating...

**Comment by falkTX** [comment] 2016-12-02 09:55
Caused by scalepoints addressed with a current value not in the list.
Fixed in https://github.com/moddevices/mod-ui/commit/7270ceef883acd35ca79bce381afb8c06091d2a1

Just in time for final 1.2.

**Closed as completed** 2016-12-02 15:48 UTC
