### ISSUE TITLE
Bug: Doubleclick on pedal messes with cables and zoom

### ISSUE THREAD

**Issue by ntonnaett** [moddevices/mod-duo-issues#40] opened 2016-05-24 12:01 UTC
## Description

Doubleclicking on an effect pedal moves the cables plugged into this pedal and focuses nearby but not on the pedal. It seems as if the coordinates of the pedal get confused.
## Expected solution

Doubleclick on a pedal should do the same as a normal click.

**Comment by falkTX** [comment] 2016-05-24 12:10
Which pedal/plugin does this apply to?
I just tried a few and I can't reproduce the issue.

**Comment by falkTX** [comment] 2016-05-24 12:11
nvm, got to reproduce it now.

need to make some connections first, zoom out, then double-click on the plugin.

**Comment by falkTX** [comment] 2016-07-15 22:10
This has been fixed in the new 1.0.0 release.

**Closed as completed by falkTX** 2016-07-15 22:10 UTC
Labels: bug, mod-ui
