### ISSUE TITLE
Renaming an assignment leads to garbage output on the display

### ISSUE THREAD

**Issue by MrBollie** [moddevices/mod-duo-issues#87] opened 2016-11-24 22:50 UTC
## Description

Renaming some assignment leads to the display showing garbage and switching to a different assigment.

## How to reproduce

 1. Add at least two icons to the pedal board
 2. Open the first's settings page
 3. Assign Knob 2 to some control
 4. Close the settings page
 5. Open the settings page of the second icon
 6. Again, click on Assign on some control
 7. In the dialog assign Knob 2 as well to that control
 8. Click save in that dialog
 9. Open the assignment dialog for that very control again
10. Click on "ADVANCED"
11. Rename the Label
12. Click Save and have a look at the internal display
 
## Expected/suggested solution

The display shouldn't switch to the prior assignment and display proper output.

## Additional information

* release: v1.2.0 RC3
* controller: e582b18

**Comment by falkTX** [comment] 2016-12-02 09:17
This is a duplicate of #10 

We should continue the discussion there. We know the issue.

**Closed as completed by falkTX** 2016-12-02 09:17 UTC
