### ISSUE TITLE
Poping noise

### ISSUE THREAD

**Issue by slickjr09** [moddevices/mod-duo-issues#52] opened 2016-06-28 17:08 UTC
So, I received my Mod Duo from the Kickstater Batch, Backer # 107. And there's been a constant poping noise. In about a 1-min time frame in will pop about 10-15 times.  and when i bypass my duo, the poping goes away. It got much worse with the 0.13 update. so i rolled it back to the 0.12.  Its very noticeable, and I cant seem to find anyone else with this issue on the forums. 

Please help, I would love to use my Duo on stage, but with this poping/crackling noise, I cant even practice with it before it has me frustrated.

Thanks

**Comment by falkTX** [comment] 2016-06-28 18:34
Sounds like xruns, this has been fixed in 0.15.
See https://forum.moddevices.com/t/release-0-15-0-testing/147/10

Please try that update and let us know if it fixes the issue.
Thanks.

**Comment by odurc** [comment] 2016-07-08 15:13
@slickjr09 can you confirm the issue is solved?

**Comment by slickjr09** [comment] 2016-07-08 15:47
Yes thank you, xruns are significantly decreased with. V.15.  I didn't
realize that's what it was. Thank you
On Jul 8, 2016 11:13 AM, "Ricardo Crudo" notifications@github.com wrote:

@slickjr09 https://github.com/slickjr09 can you confirm the issue is
solved?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
https://github.com/moddevices/mod-duo-issues/issues/52#issuecomment-231386570,
or mute the thread
https://github.com/notifications/unsubscribe/ATQZNc6wg7PQjsRxxC7iZJtw5TSat_GMks5qTmklgaJpZM4JAUqo
.

**Comment by odurc** [comment] 2016-07-08 16:09
Thank you

**Closed as completed by odurc** 2016-07-08 16:09 UTC
